[project]
name = "agenzia-ai"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "gunicorn",
    "pydantic",
    "pydantic-settings",
    "supabase",
    "mistralai",
    "twilio",
    "python-multipart",
    "thefuzz",
    "requests",
    "python-dotenv",
    "tenacity",
    "fpdf2",
    "google-auth",
    "langchain-core",
    "langchain-mistralai",
    "langgraph"
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "N", "UP", "PL"]
ignore = []

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_unused_configs = true
disallow_untyped_defs = true
